name: Python Calculator Tests
on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  run-python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Or 3.11, depending on your needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run unit tests - with coverage
        run: python -m unittest test_calculator.py